{
"project_name":"Calculator",
"project_domain":"greenswitch",
"project_main":"main_gui.html",
"project_icon":"assets/app_icon.png",
"project_mini_sdk":"4.0.1",
"project_max_sdk":"10.0.1",
"project_target_sdk":"5.0.0",
"permissions":["INTERNET","READ_SDCARD"]}